name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dishachuadhri/demo-push-git-latest
    - name: Docker push image
      run: docker login -u dishachaudhari -p ${{ secrate-DOCKER_TOKEN2 }} && docker push dishachaudheri/demo-push-git-latest
